highlighter: pygments
safe: true
exclude: [ "ghtools", "sass", "pages/README.txt", "Gemfile", "Gemfile.lock" ]
paginate: 10
paginate_path: "/archives/page/:num"

# Custom settings
sensaura_project: false # If true, this is a project.

# Default values by directory
defaults:
  # Set the default section for the site
  -
    scope:
      path: ""
    values:
      section: "blog"
  # Set the layout to use for static pages
  -
    scope:
      path: "pages"
    values:
      layout: "staticpage"
