highlighter: pygments
safe: true
exclude: [ "ghtools", "sass", "pages/README.txt", "apidocs/README.txt", "Gemfile", "Gemfile.lock" ]
paginate: 10
paginate_path: "/blog/page:num"

# Custom settings
sensaura_project: false # If true, this is a project.

# Default values by directory
defaults:
  # Set the default section for the site
  -
    scope:
      path: ""
    values:
      section: "blog"
      master: "/"
      widgets: [ "slack", "recent", "adsense" ]
  # Set the default layout for posts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  # Set the layout to use for tag pages
  -
    scope:
      path: "tags"
    values:
      layout: "tag"
  # Set the layout to use for static pages
  -
    scope:
      path: "pages"
    values:
      layout: "staticpage"
  # Set the layout to use for API documentation
  -
    scope:
      path: "apidocs"
    values:
      layout: "apidocs"
