highlighter: pygments
safe: true
exclude: [ ghtools, sass ]
paginate: 10
paginate_path: "/archives/page/:num"

# Custom settings
sensaura_project: false # If true, this is a project.

# Default values by directory
defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "staticpage"
