markdown: redcarpet
redcarpet:
  extensions: [ "lax_spacing", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]
highlighter: pygments
#safe: true
exclude: [ "ghtools", "sass", "pages/README.txt", "apidocs/README.txt", "_drafts/README.txt", "Gemfile", "Gemfile.lock" ]
paginate: 10
paginate_path: "/blog/page:num"

# Site information
name: Sensaura Project
url: http://sensaura.org

gems:
- jekyll-feed
- jekyll-sitemap

# Default values by directory
defaults:
  # Set the default section for the site
  -
    scope:
      path: ""
    values:
      section: "blog"
      master: "/"
      widgets: [ "slack", "recent" ]
  # Set the default layout for posts and drafts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  # Set the layout to use for static pages
  -
    scope:
      path: "pages"
    values:
      layout: "default"
  # Set default categories for static pages
  -
    scope:
      path: "pages/senshub"
    values:
      category: "senshub"
      section: "senshub"
  -
    scope:
      path: "pages/sensnet"
    values:
      category: "sensnet"
      section: "sensnet"
  -
    scope:
      path: "pages/sensnode"
    values:
      category: "sensnode"
      section: "sensnode"
  # Set the layout to use for API documentation
  -
    scope:
      path: "apidocs"
    values:
      layout: "apidocs"
