<div class="col s12" style="padding: 2em;">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Sensaura_Main -->
{% if jekyll.environment == "local" %}
<ins class="adsbygoogle"
     style="display:block"
     data-ad-test="on"
     data-ad-client="ca-pub-2706317131001123"
     data-ad-slot="9897912892"
     data-ad-format="auto"></ins>
{% else %}
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2706317131001123"
     data-ad-slot="9897912892"
     data-ad-format="auto"></ins>
{% endif %}
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
