<!-- Disqus comment thread for page -->
<div class="col s12" id="disqus_thread"></div>
<script>
var disqus_config = function () {
this.page.developer = 1; // Comment out when the site is live
this.page.identifier = "{{ page.url }}";
};
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//sensaura.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
