<div class="widget blue-grey lighten-5">
  <div class="title">Discuss on Slack</div>
  <p>
    <img src="/images/logos/slack-chat-64.png" alt="" class="left">
    The Sensaura project has it's very own Slack team - <a href="https://docs.google.com/a/sensaura.org/forms/d/1PTCu0A5u7OZh136BmPCS3jx0VPoCGIwvEc2fYyVhNYQ/viewform">click here</a>
    to request an invitation and one will be automatically sent to you.
  </p>
</div>
